config/routes.rb
Rails.application.routes.draw do
  get "weather/search"
  get "weather/results"
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/*
  get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker
  get "manifest" => "rails/pwa#manifest", as: :pwa_manifest

  # Defines the root path route ("/")
  root "weather#search"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Only allow modern browsers supporting webp images, web push, badges, import maps, CSS nesting, and CSS :has.
  allow_browser versions: :modern
end

app/controllers/weather_controller.rb
class WeatherController < ApplicationController
  def search
  end

  def results
    @cache_exists = Rails.cache.exist?(zipcode_param)
    @zipcode_param = zipcode_param
    @weather_results = begin
      Rails.cache.fetch(zipcode_param, expires_in: 30.minutes) do
        weather_client.current_zip(zipcode_param)
      end
    rescue
      nil
    end
  end

  def zipcode_param
    params.require(:zipcode)
  end

  def weather_api_key
    Rails.application.credentials.weather_api_key
  end

  def weather_client
     @weather_client ||= OpenWeather::Client.new(
      api_key: weather_api_key,
      units: "imperial"
    )
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= content_for(:title) || "Weather Interview" %></title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <meta name="apple-mobile-web-app-capable" content="yes">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= yield :head %>

    <link rel="manifest" href="/manifest.json">
    <link rel="icon" href="/icon.png" type="image/png">
    <link rel="icon" href="/icon.svg" type="image/svg+xml">
    <link rel="apple-touch-icon" href="/icon.png">
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_include_tag "application", "data-turbo-track": "reload", type: "module" %>

    <style>
      .bd-placeholder-img {
        font-size: 1.125rem;
        text-anchor: middle;
        -webkit-user-select: none;
        -moz-user-select: none;
        user-select: none;
      }

      @media (min-width: 768px) {
        .bd-placeholder-img-lg {
          font-size: 3.5rem;
        }
      }

      .b-example-divider {
        width: 100%;
        height: 3rem;
        background-color: rgba(0, 0, 0, .1);
        border: solid rgba(0, 0, 0, .15);
        border-width: 1px 0;
        box-shadow: inset 0 .5em 1.5em rgba(0, 0, 0, .1), inset 0 .125em .5em rgba(0, 0, 0, .15);
      }

      .b-example-vr {
        flex-shrink: 0;
        width: 1.5rem;
        height: 100vh;
      }

      .bi {
        vertical-align: -.125em;
        fill: currentColor;
      }

      .nav-scroller {
        position: relative;
        z-index: 2;
        height: 2.75rem;
        overflow-y: hidden;
      }

      .btn-bd-primary {
        --bd-violet-bg: #712cf9;
        --bd-violet-rgb: 112.520718, 44.062154, 249.437846;

        --bs-btn-font-weight: 600;
        --bs-btn-color: var(--bs-white);
        --bs-btn-bg: var(--bd-violet-bg);
        --bs-btn-border-color: var(--bd-violet-bg);
        --bs-btn-hover-color: var(--bs-white);
        --bs-btn-hover-bg: #6528e0;
        --bs-btn-hover-border-color: #6528e0;
        --bs-btn-focus-shadow-rgb: var(--bd-violet-rgb);
        --bs-btn-active-color: var(--bs-btn-hover-color);
        --bs-btn-active-bg: #5a23c8;
        --bs-btn-active-border-color: #5a23c8;
      }

      .bd-mode-toggle {
        z-index: 1500;
      }

      .bd-mode-toggle .dropdown-menu .active .bi {
        display: block !important;
      }

      .text-initial {
        text-align: initial;
      }
    </style>
  </head>

<body class="d-flex h-100 text-center text-bg-dark">
    
<div class="cover-container d-flex w-100 h-100 p-3 mx-auto flex-column">
  <header class="mb-auto">
    <div>
      <h3 class="float-md-start mb-0">Local Weather</h3>
    </div>
  </header>

  <main class="px-3">
    <%= yield %>
  </main>

</div>

    </body>
    
</html>

app/views/weather/_form.html.erb
<%= form_with url: weather_results_path, class: 'form-inline mt-4', method: :get do |form| %>
  <div class="form-group row mx-sm-3 mb-2">
    <%= form.label :zipcode, "Zipcode:",  class: "col-sm-2 col-form-label" %>
    <div class="col-sm-8">
      <%= form.text_field :zipcode, class: "form-control" %>
    </div>
    <div class="col-sm-2">
      <%= form.submit "Search", class: "btn btn-primary mb-2" %>
    </div>
  </div>
<% end %>

app/views/weather/results.html.erb
<% if @weather_results.present? %>
<div class="row mt-4 text-initial">
  <div class="offset-md-4 col-md-4">
    Current Temperature: <%= @weather_results.main.temp %>F 
  </div>
  <div class="offset-md-4 col-md-4">
    Max Temperature: <%= @weather_results.main.temp_max %>F 
  </div>
  <div class="offset-md-4 col-md-4">
    Min Temperature: <%= @weather_results.main.temp_min %>F 
  </div>
  <div class="offset-md-4 col-md-4">
    Zipcode: <%= @zipcode_param %>
  </div>
  <div class="offset-md-4 col-md-4">
    Cached Results? <%= @cache_exists ? "Yes" : "No" %>
  </div>
</div>
<% else %>
<div class="row mt-4">
  <div class="offset-md-4 col-md-4">
    <h3>Sorry, that zipcode is invalid. Please try again with a valid zipcode.</h3>
  </div>
</div>
<% end %>


<%= render partial: 'form' %>

app/views/weather/search.html.erb
<div class="row mt-4">
  <h1>Weather Search</h1>
</div>

<%= render partial: 'form' %>